//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adisyon_fis
    {
        public long id { get; set; }
        public Nullable<long> masa_id { get; set; }
        public Nullable<int> adisyon_no { get; set; }
        public Nullable<long> cari_id { get; set; }
        public Nullable<long> gr_id { get; set; }
        public Nullable<int> durumu { get; set; }
        public Nullable<System.DateTime> acilis_tarihi { get; set; }
        public Nullable<System.DateTime> kapanis_tarihi { get; set; }
        public string ozel_kodu { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string ticari_unvani { get; set; }
        public string aciklama { get; set; }
        public Nullable<long> garson_cari_id { get; set; }
        public string garson_adi { get; set; }
        public string garson_soyadi { get; set; }
        public string adres { get; set; }
        public Nullable<int> kisi_sayisi { get; set; }
        public Nullable<double> ara_tutar { get; set; }
        public Nullable<double> indirim { get; set; }
        public Nullable<double> toplam_tutar { get; set; }
        public Nullable<long> fatura_id { get; set; }
        public Nullable<long> rezervasyon_id { get; set; }
        public Nullable<System.DateTime> alarm_tarih { get; set; }
        public Nullable<short> indirim_var { get; set; }
        public Nullable<double> indirim_orani { get; set; }
        public Nullable<short> resmi_adisyon_son_satir { get; set; }
        public Nullable<long> sube_id { get; set; }
        public Nullable<short> offline_durum { get; set; }
        public Nullable<short> teslim_durum { get; set; }
        public Nullable<System.DateTime> cikis_zamani { get; set; }
        public Nullable<System.DateTime> donus_zamani { get; set; }
        public Nullable<double> otomatik_ekstra { get; set; }
        public Nullable<long> kredi_karti_id { get; set; }
        public string adisyon_no_goruntu { get; set; }
        public Nullable<double> iptal_toplam { get; set; }
        public Nullable<long> doviz_birimi_id { get; set; }
        public string telefon { get; set; }
        public string barkodu { get; set; }
        public Nullable<short> paket_ic_dis { get; set; }
        public Nullable<short> muhasebelendi { get; set; }
        public string cari_grubu { get; set; }
        public string adisyon_no_yazdir { get; set; }
        public string offline_guid { get; set; }
        public Nullable<short> yazdirildi { get; set; }
        public string evrak_no { get; set; }
    }
}
