//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adisyon_hareket_yazdirma
    {
        public long id { get; set; }
        public Nullable<long> adisyon_hareket_id { get; set; }
        public Nullable<long> fis_id { get; set; }
        public string urun_adi { get; set; }
        public Nullable<double> fiyati { get; set; }
        public Nullable<double> miktari { get; set; }
        public Nullable<double> toplam { get; set; }
        public Nullable<double> siralama_kodu { get; set; }
        public Nullable<short> iptal { get; set; }
        public Nullable<long> grup_id { get; set; }
        public Nullable<short> yazdirma_tip { get; set; }
    }
}
