//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adisyon_stok_detay
    {
        public long id { get; set; }
        public Nullable<long> stok_id { get; set; }
        public string cinsi { get; set; }
        public Nullable<double> fiyati { get; set; }
        public Nullable<long> stok_id_2 { get; set; }
        public Nullable<double> miktar { get; set; }
        public Nullable<short> otomatik { get; set; }
        public Nullable<short> donusum { get; set; }
        public Nullable<double> dusulecek_miktar { get; set; }
        public Nullable<long> dusulecek_birim_id { get; set; }
        public string departman { get; set; }
        public Nullable<short> eklerken_sor { get; set; }
        public Nullable<long> depo_id { get; set; }
        public Nullable<long> sube_id { get; set; }
        public Nullable<long> menu_stok_id { get; set; }
        public Nullable<short> ayni_depo_kullan { get; set; }
    }
}
