//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adisyon_hareket
    {
        public long id { get; set; }
        public Nullable<long> fis_id { get; set; }
        public Nullable<long> stok_id { get; set; }
        public string stok_kodu { get; set; }
        public string urun_adi { get; set; }
        public Nullable<double> fiyati { get; set; }
        public Nullable<double> miktari { get; set; }
        public Nullable<double> toplam { get; set; }
        public Nullable<long> ekleyen { get; set; }
        public Nullable<long> aciklama_hareket_id { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<double> temel_fiyat { get; set; }
        public Nullable<double> siralama_kodu { get; set; }
        public Nullable<short> iptal { get; set; }
        public string iptal_nedeni { get; set; }
        public Nullable<short> menu { get; set; }
        public Nullable<long> aciklama_id { get; set; }
        public Nullable<long> grup_id { get; set; }
        public Nullable<short> yazdirildi { get; set; }
        public Nullable<double> yazdirilan_miktar { get; set; }
        public string aciklama { get; set; }
        public Nullable<long> birim_id { get; set; }
        public Nullable<System.DateTime> sure_baslama_tarihi { get; set; }
        public Nullable<System.DateTime> sure_bitis_tarihi { get; set; }
        public string tarife { get; set; }
        public Nullable<double> indirim_orani { get; set; }
        public Nullable<long> on_odeme_id { get; set; }
        public Nullable<long> mutfak_yazdirma_id { get; set; }
        public Nullable<double> kdv_orani { get; set; }
        public string muh_kodu_genel { get; set; }
        public Nullable<short> ikram_durum { get; set; }
        public Nullable<double> ikram_fiyat { get; set; }
        public Nullable<long> iptal_eden { get; set; }
        public Nullable<System.DateTime> iptal_zaman { get; set; }
        public Nullable<System.DateTime> teslim_zaman { get; set; }
        public Nullable<int> servis_suresi { get; set; }
        public Nullable<int> teslim_gecen_sure { get; set; }
        public string barkodu { get; set; }
        public Nullable<long> stok_birim_id { get; set; }
        public string seri_no { get; set; }
        public Nullable<long> aciklama_hareket_id_2 { get; set; }
        public Nullable<long> garson_id { get; set; }
        public Nullable<short> hazir { get; set; }
        public Nullable<long> yazdirma_hareket_id { get; set; }
    }
}
