//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adisyon_buton
    {
        public long id { get; set; }
        public Nullable<long> grup_id { get; set; }
        public Nullable<long> stok_id { get; set; }
        public Nullable<int> sol { get; set; }
        public Nullable<int> ust { get; set; }
        public string birimi { get; set; }
        public Nullable<int> genislik { get; set; }
        public Nullable<int> yukseklik { get; set; }
        public Nullable<short> pda_sira { get; set; }
        public string sube_id { get; set; }
        public string grubu { get; set; }
        public string offline_id { get; set; }
        public Nullable<short> ikram { get; set; }
        public Nullable<int> background_color { get; set; }
        public Nullable<int> font_color { get; set; }
    }
}
