//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adisyon_odeme
    {
        public long id { get; set; }
        public Nullable<long> adisyon_fis_id { get; set; }
        public Nullable<short> islem_turu { get; set; }
        public Nullable<long> banka_id { get; set; }
        public Nullable<long> banka_hesap_id { get; set; }
        public Nullable<long> pos_detay_id { get; set; }
        public Nullable<long> kasa_id { get; set; }
        public Nullable<double> tutar { get; set; }
        public string simge { get; set; }
    }
}
