//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class banka_kk_detay
    {
        public long id { get; set; }
        public long banka_id { get; set; }
        public string tanimi { get; set; }
        public string kk_no { get; set; }
        public Nullable<short> hes_kes_gunu { get; set; }
        public Nullable<short> son_odm_gunu { get; set; }
        public Nullable<int> hesap_id { get; set; }
        public string ek_bilgi { get; set; }
        public Nullable<short> kk_sube_ortak_kulan { get; set; }
        public Nullable<double> kart_limiti { get; set; }
        public Nullable<short> aktif { get; set; }
    }
}
