//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class banka_adi
    {
        public long id { get; set; }
        public string subesi { get; set; }
        public string yetkilisi { get; set; }
        public string telefon_1 { get; set; }
        public string telefon_2 { get; set; }
        public string faks { get; set; }
        public string e_posta { get; set; }
        public string web { get; set; }
        public string adresi { get; set; }
        public string not_1 { get; set; }
        public string not_2 { get; set; }
        public Nullable<short> pos_kullan { get; set; }
        public Nullable<short> kk_kullan { get; set; }
        public string muh_kodu_slip { get; set; }
        public string muh_kodu_kredi { get; set; }
        public string muh_kodu_slip_2 { get; set; }
        public Nullable<short> cek_kullan { get; set; }
        public string muh_kodu_cek { get; set; }
        public Nullable<long> kaydeden { get; set; }
        public Nullable<long> degistiren { get; set; }
        public Nullable<System.DateTime> degistirme_tarihi { get; set; }
        public string resmi_tatil_tanimi { get; set; }
        public string hesap_no { get; set; }
        public string banka_adi1 { get; set; }
        public string sube_kodu { get; set; }
        public Nullable<short> sanalpos_kullan { get; set; }
        public string sanalpos_isletme_kodu { get; set; }
        public string sanalpos_kullanici_adi { get; set; }
        public string sanalpos_kullanici_sifre { get; set; }
        public string sanalpos_host { get; set; }
        public Nullable<short> sanalpos_diger_banka { get; set; }
        public string banka_sube_kodu { get; set; }
        public Nullable<short> offline_durum { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public string muhkodu_pos_iade_kes { get; set; }
    }
}
