//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class banka_pos_detay
    {
        public long id { get; set; }
        public Nullable<long> banka_id { get; set; }
        public string tanimi { get; set; }
        public Nullable<double> vade_orani { get; set; }
        public Nullable<short> vade_gunu { get; set; }
        public Nullable<short> taksit_sayisi { get; set; }
        public string bagli_hesap_no { get; set; }
        public Nullable<double> satis_vade_orani { get; set; }
        public Nullable<short> prvz_kesinti_tipi { get; set; }
        public Nullable<short> ortalama_vade_gunu { get; set; }
        public string muh_kodu_pos { get; set; }
    }
}
