//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class banka_hesap
    {
        public long id { get; set; }
        public Nullable<long> banka_id { get; set; }
        public string hesap_no { get; set; }
        public string hesap_turu { get; set; }
        public string muh_kodu { get; set; }
        public Nullable<short> vadeli { get; set; }
        public string tanimi { get; set; }
        public Nullable<double> kredi_limiti { get; set; }
        public Nullable<short> cek_kredi_hesabi { get; set; }
        public string iban_no { get; set; }
        public Nullable<System.DateTime> acilis_tarihi { get; set; }
        public Nullable<System.DateTime> kapanis_tarihi { get; set; }
        public Nullable<double> rotatif_kr_limiti { get; set; }
        public string swift { get; set; }
        public Nullable<short> sube_ortak_kullan { get; set; }
        public string muh_kodu_cek_takas { get; set; }
        public string muh_kodu_cek_teminat { get; set; }
        public string muh_kodu_senet_takas { get; set; }
    }
}
