//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class banka_cek_senet
    {
        public long id { get; set; }
        public long banka_id { get; set; }
        public string tanimi { get; set; }
        public Nullable<int> baslangic_no { get; set; }
        public Nullable<int> bitis_no { get; set; }
        public Nullable<int> hazir_no { get; set; }
        public string bagli_hesap_no { get; set; }
        public string basina_ekle { get; set; }
        public Nullable<short> basamak_sayisi { get; set; }
    }
}
