//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class banka_hareket
    {
        public long id { get; set; }
        public string evrak_no { get; set; }
        public string ozel_kodu { get; set; }
        public Nullable<System.DateTime> tarihi { get; set; }
        public Nullable<System.DateTime> vadesi { get; set; }
        public Nullable<short> islem_turu { get; set; }
        public string aciklama { get; set; }
        public string bag_no { get; set; }
        public string muh_hes_kodu { get; set; }
        public Nullable<long> trs_id { get; set; }
        public Nullable<double> provizyon_tutari { get; set; }
        public Nullable<double> islem_tutari { get; set; }
        public Nullable<short> silindi { get; set; }
        public Nullable<long> kaydeden { get; set; }
        public Nullable<long> degistiren { get; set; }
        public Nullable<System.DateTime> degistirme_tarihi { get; set; }
        public Nullable<double> tutar_borc { get; set; }
        public Nullable<double> tutar_alacak { get; set; }
        public Nullable<long> hesap_id { get; set; }
        public string pos_tanimi { get; set; }
        public Nullable<double> kpb_tutari { get; set; }
        public Nullable<long> cari_id { get; set; }
        public Nullable<short> entegrasyon_durumu { get; set; }
        public Nullable<long> sube_id { get; set; }
        public Nullable<System.DateTime> tarihi_2 { get; set; }
        public Nullable<System.DateTime> vadesi_2 { get; set; }
        public Nullable<short> offline_durum { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public string edf_belge_turu { get; set; }
        public string edf_belge_turu_dig { get; set; }
        public Nullable<short> hareket_turu { get; set; }
        public Nullable<double> doviz_alis { get; set; }
        public Nullable<double> doviz_satis { get; set; }
    }
}
