//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class basit_uretim
    {
        public long id { get; set; }
        public Nullable<long> stok__id { get; set; }
        public Nullable<short> recete_tipi { get; set; }
        public string uretim_kodu { get; set; }
        public string uretim_miktari { get; set; }
        public Nullable<double> miktari { get; set; }
        public string hesap { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public string aciklama { get; set; }
        public string ozel_kodu { get; set; }
        public string depo_adi { get; set; }
        public Nullable<double> diger_maliyetler { get; set; }
        public Nullable<short> gm_entegrasyon { get; set; }
        public string DIGMLY_HESAP_KODU { get; set; }
        public string sube_kodu { get; set; }
        public Nullable<double> S_URETIM_MIKTARI { get; set; }
        public Nullable<double> S_FIRE_MIKTARI { get; set; }
        public Nullable<double> S_BRM_MAMUL_MALIYETI { get; set; }
        public Nullable<double> S_BRM_MAMUL_FIRE_MLY { get; set; }
        public Nullable<double> S_BRM_DIGER_MALIYETLER { get; set; }
        public Nullable<double> S_BRM_ARA_MALIYET { get; set; }
        public Nullable<double> S_BRM_TOPLAM_MALIYET { get; set; }
        public Nullable<double> S_TPL_MAMUL_MALIYETI { get; set; }
        public Nullable<double> S_TPL_MAMUL_FIRE_MLY { get; set; }
        public Nullable<double> S_TPL_DIGER_MALIYETLER { get; set; }
        public Nullable<double> S_TPL_FIRE_MALIYETI { get; set; }
        public Nullable<double> S_TPL_TOPLAM_MALIYET { get; set; }
        public Nullable<double> S_FIRE_ORANI { get; set; }
        public Nullable<double> S_NET_URETILEN { get; set; }
        public Nullable<double> S_BRM_URETIM_FIREMLYT { get; set; }
        public Nullable<System.DateTime> S_URETIM_TARIHI { get; set; }
        public string S_URETIM_ACIKLAMA { get; set; }
        public Nullable<short> sube_ortak { get; set; }
        public Nullable<long> recete_id { get; set; }
        public Nullable<double> doviz_kuru { get; set; }
        public Nullable<short> DURUMU { get; set; }
        public Nullable<short> ENTEGRASYON_YAPILDI { get; set; }
        public Nullable<long> BLSPHRKODU { get; set; }
        public Nullable<short> STOK_BLOKE { get; set; }
        public string kaydeden { get; set; }
        public string degistiren { get; set; }
        public Nullable<System.DateTime> degistirme_tarihi { get; set; }
    }
}
