//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bekleme_listesi
    {
        public long id { get; set; }
        public string bekleme_adi { get; set; }
        public Nullable<long> kaydeden { get; set; }
        public Nullable<long> cari_id { get; set; }
        public Nullable<long> fatura_id { get; set; }
        public string unvani { get; set; }
        public string cari_yetkili { get; set; }
        public string fis_notu { get; set; }
        public Nullable<short> kdv_durumu { get; set; }
        public Nullable<double> toplam { get; set; }
        public string dataset { get; set; }
    }
}
