//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cari_izinler
    {
        public int id { get; set; }
        public Nullable<int> cari_id { get; set; }
        public string izin_sebebi { get; set; }
        public string izin_cesidi { get; set; }
        public Nullable<int> izin_suresi { get; set; }
        public Nullable<int> izin_hakki { get; set; }
        public string izin_baslangic_tarihi { get; set; }
        public string izin_baslangic_saati { get; set; }
        public string izin_bitis_tarihi { get; set; }
        public string izin_bitis_saati { get; set; }
        public string izin_isbasi_tarihi { get; set; }
        public string izin_isbasi_saati { get; set; }
        public Nullable<int> izin_kullanilan_izin { get; set; }
        public Nullable<int> izin_kalan_izin { get; set; }
        public Nullable<short> silindi { get; set; }
    }
}
