//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cari_hareket_onceki
    {
        public long id { get; set; }
        public long cari_id { get; set; }
        public string ozel_kodu { get; set; }
        public string evrak_no { get; set; }
        public Nullable<System.DateTime> tarihi { get; set; }
        public Nullable<System.DateTime> vadesi { get; set; }
        public Nullable<short> muh_durum { get; set; }
        public string muh_hes_kodu { get; set; }
        public Nullable<short> doviz_kullan { get; set; }
        public Nullable<double> doviz_alis { get; set; }
        public Nullable<double> doviz_satis { get; set; }
        public Nullable<short> kpb_doviz { get; set; }
        public Nullable<int> doviz_birimi_id { get; set; }
        public Nullable<short> doviz_hes_isle { get; set; }
        public string aciklama { get; set; }
        public Nullable<int> kasa_id { get; set; }
        public string banka_adi { get; set; }
        public string kredi_karti_detay { get; set; }
        public string entegrasyon { get; set; }
        public Nullable<double> kpb_btut { get; set; }
        public Nullable<double> kpb_atut { get; set; }
        public Nullable<double> doviz_btut { get; set; }
        public Nullable<double> doviz_atut { get; set; }
        public Nullable<long> transfer_kodu { get; set; }
        public Nullable<long> teminat_id { get; set; }
        public Nullable<short> silindi { get; set; }
        public Nullable<long> kaydeden { get; set; }
        public Nullable<long> degistiren { get; set; }
        public Nullable<System.DateTime> degistirme_tarihi { get; set; }
        public Nullable<short> islem_turu { get; set; }
        public Nullable<long> blbnhskodu { get; set; }
        public string pos_detay { get; set; }
        public Nullable<short> cek_odendi { get; set; }
        public Nullable<short> gm_entegrasyon { get; set; }
        public Nullable<double> provizyon_tutari { get; set; }
        public string makbuz_no { get; set; }
        public Nullable<short> fatura_durumu { get; set; }
        public Nullable<short> bonus_miktari { get; set; }
        public Nullable<double> banka_islem_ucreti { get; set; }
        public Nullable<double> doviz_btut_2 { get; set; }
        public Nullable<double> doviz_atut_2 { get; set; }
        public Nullable<double> doviz_satis_2 { get; set; }
        public Nullable<double> doviz_alis_2 { get; set; }
        public Nullable<int> doviz_birimi_2_id { get; set; }
        public Nullable<System.DateTime> pos_vade_tarihi { get; set; }
        public Nullable<short> kp_devir { get; set; }
        public Nullable<long> sube_id { get; set; }
        public Nullable<short> taksit_sayisi { get; set; }
        public Nullable<System.DateTime> tarihi_2 { get; set; }
        public Nullable<System.DateTime> vadesi_2 { get; set; }
        public Nullable<short> offline_durum { get; set; }
        public Nullable<short> kk_vade_engelleme { get; set; }
        public string source_app { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public string ozel_kodu_2 { get; set; }
        public string edf_belge_turu { get; set; }
        public string edf_belge_turu_dig { get; set; }
        public string ent_grubu { get; set; }
        public string ent_ara_grubu { get; set; }
        public string ent_alt_grubu { get; set; }
        public string offline_guid { get; set; }
        public Nullable<long> blithalatkodu { get; set; }
        public Nullable<long> fatura_id { get; set; }
    }
}
