//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cari_notlar
    {
        public long id { get; set; }
        public long cari_id { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string not_kodu { get; set; }
        public string aciklama { get; set; }
        public Nullable<bool> silindi { get; set; }
        public Nullable<int> kayit_yapan { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public Nullable<int> degisiklik_yapan { get; set; }
        public Nullable<System.DateTime> degisiklik_tarihi { get; set; }
    }
}
