//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cari_yeni
    {
        public long id { get; set; }
        public string cari_kodu { get; set; }
        public string ticari_unvani { get; set; }
        public string ozel_kodu_1 { get; set; }
    }
}
