//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cari_servis_bilgiler
    {
        public long id { get; set; }
        public long cari_id { get; set; }
        public string urun_adi { get; set; }
        public string markasi { get; set; }
        public string modeli { get; set; }
        public string seri_no { get; set; }
        public Nullable<bool> aktif { get; set; }
        public Nullable<bool> silindi { get; set; }
        public Nullable<int> kayit_yapan { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public Nullable<int> degisiklik_yapan { get; set; }
        public Nullable<System.DateTime> degisiklik_tarihi { get; set; }
        public string cari_kodu { get; set; }
        public string ticari_unvani { get; set; }
        public Nullable<System.DateTime> proje_baslangic_tarihi { get; set; }
        public Nullable<System.DateTime> proje_bitis_tarihi { get; set; }
        public string calistigi_bolum { get; set; }
        public Nullable<System.DateTime> ssk_baslangic_tarihi { get; set; }
        public Nullable<System.DateTime> personel_sozlesme_tarihi { get; set; }
        public string aciklama { get; set; }
    }
}
