//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cari_yetkililer
    {
        public long id { get; set; }
        public Nullable<long> cari_id { get; set; }
        public string yetkili_kodu { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string departmani { get; set; }
        public string gorevi { get; set; }
        public string dahili_no { get; set; }
        public string cep_telefonu { get; set; }
        public Nullable<short> sms_gonder { get; set; }
        public string e_posta { get; set; }
        public Nullable<System.DateTime> dogum_tarihi { get; set; }
        public string kullanici_adi { get; set; }
        public string parola { get; set; }
        public Nullable<bool> silindi { get; set; }
        public Nullable<int> kayit_yapan { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public Nullable<int> degisiklik_yapan { get; set; }
        public Nullable<System.DateTime> degisiklik_tarihi { get; set; }
    }
}
