//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cari
    {
        public long id { get; set; }
        public string cari_kodu { get; set; }
        public string ticari_unvani { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string adresi { get; set; }
        public string ulkesi { get; set; }
        public string ili { get; set; }
        public string ilcesi { get; set; }
        public string grubu { get; set; }
        public string ara_grubu { get; set; }
        public string alt_grubu { get; set; }
        public string telefon_1 { get; set; }
        public string telefon_2 { get; set; }
        public string ev_telefonu { get; set; }
        public string cep_telefonu { get; set; }
        public string faks { get; set; }
        public string ozel_kodu_1 { get; set; }
        public string ozel_kodu_2 { get; set; }
        public string ozel_kodu_3 { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public Nullable<System.DateTime> ozel_tarih { get; set; }
        public string vergi_dairesi { get; set; }
        public string vergi_no { get; set; }
        public string tc_kimlik_no { get; set; }
        public Nullable<short> durumu { get; set; }
        public Nullable<bool> ozel_iskonto_cb { get; set; }
        public Nullable<double> ozel_iskonto_tb { get; set; }
        public Nullable<bool> iskonto_1_cb { get; set; }
        public Nullable<double> iskonto_1_tb { get; set; }
        public Nullable<bool> iskonto_2_cb { get; set; }
        public Nullable<double> iskonto_2_tb { get; set; }
        public Nullable<bool> iskonto_3_cb { get; set; }
        public Nullable<double> iskonto_3_tb { get; set; }
        public Nullable<double> vade_orani { get; set; }
        public Nullable<short> kullanilacak_stok_fiyati { get; set; }
        public string karekod_transfer { get; set; }
        public Nullable<short> vade_kullan_ay { get; set; }
        public Nullable<short> vade_kullan_gun { get; set; }
        public Nullable<short> riskli_musteri { get; set; }
        public string risk_notlari { get; set; }
        public bool kurumsalfirma { get; set; }
        public string mesaj_metni { get; set; }
        public Nullable<short> alici_grubu { get; set; }
        public Nullable<short> yaslandirma_grubu { get; set; }
        public Nullable<short> doviz_hesabi_kullan { get; set; }
        public string varsayilan_doviz_birimi { get; set; }
        public Nullable<short> taksitli_islem { get; set; }
        public Nullable<short> cuzdan_turu { get; set; }
        public string cuzdan_seri { get; set; }
        public string seri_no { get; set; }
        public string nufus_tc_kimlik_no { get; set; }
        public string baba_adi { get; set; }
        public string ana_adi { get; set; }
        public string dogum_yeri { get; set; }
        public Nullable<System.DateTime> dogum_tarihi { get; set; }
        public Nullable<short> medeni_hali { get; set; }
        public string uyrugu { get; set; }
        public Nullable<short> cinsiyeti { get; set; }
        public string dini { get; set; }
        public string nufus_ili { get; set; }
        public string nufus_ilcesi { get; set; }
        public string mahalle_koy { get; set; }
        public string cilt_no { get; set; }
        public string aile_sira_no { get; set; }
        public string sira_no { get; set; }
        public string nufus_dairesi { get; set; }
        public string verilis_nedeni { get; set; }
        public Nullable<short> kan_grubu { get; set; }
        public string kredi_karti_1 { get; set; }
        public string kredi_karti_2 { get; set; }
        public string icq { get; set; }
        public string e_posta { get; set; }
        public string web { get; set; }
        public string not_1 { get; set; }
        public string not_2 { get; set; }
        public string not_3 { get; set; }
        public string kullanici_adi { get; set; }
        public string sifre { get; set; }
        public string banka_1_banka_adi { get; set; }
        public string banka_1_sube_adi { get; set; }
        public string banka_1_sube_kodu { get; set; }
        public string banka_1_hesap_no { get; set; }
        public string banka_1_iban_no { get; set; }
        public string banka_1_swift_kodu { get; set; }
        public string banka_2_banka_adi { get; set; }
        public string banka_2_sube_adi { get; set; }
        public string banka_2_sube_kodu { get; set; }
        public string banka_2_hesap_no { get; set; }
        public string banka_2_iban_no { get; set; }
        public string banka_2_swift_kodu { get; set; }
        public string adi_soyadi { get; set; }
        public string ozel_bilgiler_tc_kimlik_no { get; set; }
        public string ozel_bilgiler_telefon_1 { get; set; }
        public string ozel_bilgiler_telefon_2 { get; set; }
        public string ozel_bilgiler_adresi { get; set; }
        public string fatura_adresi { get; set; }
        public string fatura_ulkesi { get; set; }
        public string fatura_ili { get; set; }
        public string fatura_ilcesi { get; set; }
        public string sevk_adresi { get; set; }
        public string sevk_ulkesi { get; set; }
        public string sevk_ili { get; set; }
        public string sevk_ilcesi { get; set; }
        public Nullable<bool> pazarlama_sistemi_kullan { get; set; }
        public Nullable<double> urunden_alacagi_yuzde { get; set; }
        public Nullable<double> iscilikten_alacagi_yuzde { get; set; }
        public string pda_sifresi { get; set; }
        public Nullable<long> bilg_cari_kodu { get; set; }
        public Nullable<bool> garson { get; set; }
        public string garson_pda_sifresi { get; set; }
        public Nullable<bool> servis_personeli { get; set; }
        public string hesap { get; set; }
        public Nullable<double> acik_hesap { get; set; }
        public Nullable<double> irsaliye_riski { get; set; }
        public Nullable<double> siparis_riski { get; set; }
        public Nullable<double> toplam_risk { get; set; }
        public Nullable<bool> kredi_asiminda_uyar { get; set; }
        public Nullable<bool> tahsil_edilmemisleri_dahil_etme { get; set; }
        public Nullable<double> odenmeyen_cekler_k { get; set; }
        public Nullable<double> odenmeyen_cekler_c { get; set; }
        public Nullable<double> odenmeyen_senetler_k { get; set; }
        public Nullable<double> odenmeyen_senetler_c { get; set; }
        public Nullable<short> silindi { get; set; }
        public Nullable<int> cari_kayit_yapan { get; set; }
        public Nullable<System.DateTime> cari_kayit_tarihi { get; set; }
        public Nullable<int> cari_degisiklik_yapan { get; set; }
        public Nullable<System.DateTime> cari_degisiklik_tarihi { get; set; }
        public string ozel_guvenlik_belge_izin_no { get; set; }
        public string genel_kolluk { get; set; }
        public string police_no { get; set; }
        public string police_baslangic_tarihi { get; set; }
        public string police_bitis_tarihi { get; set; }
        public string sozlesme_bitis_tarihi { get; set; }
        public string evrak_kontrol { get; set; }
        public string resim_yolu { get; set; }
        public Nullable<short> proje { get; set; }
        public string gorevi { get; set; }
        public string ogg_kart_no { get; set; }
        public string ogg_gecerlilik_suresi { get; set; }
        public string silah_durumu { get; set; }
        public string ssk_baslangic_tarihi { get; set; }
        public string egitim_durumu { get; set; }
        public string EIScenarioId { get; set; }
        public string EIType { get; set; }
    }
}
