//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cek_senet
    {
        public long id { get; set; }
        public Nullable<short> evrak_turu { get; set; }
        public Nullable<short> evrak_durumu { get; set; }
        public Nullable<short> banka_durumu { get; set; }
        public Nullable<System.DateTime> tarihi { get; set; }
        public Nullable<System.DateTime> vadesi { get; set; }
        public Nullable<System.DateTime> odeme_tarihi { get; set; }
        public string banka_adi { get; set; }
        public string kasa_adi { get; set; }
        public string evrak_no { get; set; }
        public string keside_yeri { get; set; }
        public string evrak_banka { get; set; }
        public string banka_subesi { get; set; }
        public string banka_hesap_no { get; set; }
        public Nullable<short> kpb_doviz { get; set; }
        public Nullable<double> kpb_tutari { get; set; }
        public Nullable<double> doviz_tutari { get; set; }
        public string doviz_birimi { get; set; }
        public Nullable<double> doviz_alis { get; set; }
        public Nullable<double> doviz_satis { get; set; }
        public string odks_adi { get; set; }
        public string odks_soyadi { get; set; }
        public string odks_unvani { get; set; }
        public string odks_telefon { get; set; }
        public string odks_adresi { get; set; }
        public string kefil_adi { get; set; }
        public string kefil_soyadi { get; set; }
        public string kefil_vergi_no { get; set; }
        public string kefil_vergi_dr { get; set; }
        public string kefil_adresi { get; set; }
        public string kefil_telefon { get; set; }
        public string ciro_1 { get; set; }
        public string ciro_2 { get; set; }
        public string not_1 { get; set; }
        public string not_2 { get; set; }
        public Nullable<short> teminat_mi { get; set; }
        public string kaydeden { get; set; }
        public string degistiren { get; set; }
        public Nullable<System.DateTime> degistirme_tarihi { get; set; }
        public Nullable<long> banka_hesap_id { get; set; }
        public Nullable<short> silindi { get; set; }
        public Nullable<long> cari_id { get; set; }
        public Nullable<long> ciro_cari_id { get; set; }
        public Nullable<short> protesto_oldu { get; set; }
        public string odks_cari_kodu { get; set; }
        public string cek_tanimi { get; set; }
        public Nullable<short> gm_entegrasyon { get; set; }
        public Nullable<short> doviz_hesabina_isle { get; set; }
        public string ozel_kodu { get; set; }
        public Nullable<short> havuz_sistemi { get; set; }
        public Nullable<double> teminat_senet_devir { get; set; }
        public Nullable<short> devir { get; set; }
        public string gm_portfoy_hs_kodu { get; set; }
        public Nullable<short> asil_borclu { get; set; }
        public string ozel_kodu_2 { get; set; }
        public Nullable<System.DateTime> tarihi_2 { get; set; }
        public Nullable<System.DateTime> vadesi_2 { get; set; }
        public Nullable<short> offline_durum { get; set; }
        public string source_app { get; set; }
        public Nullable<double> odenen_tutar_devir { get; set; }
        public Nullable<double> odenen_tutar { get; set; }
        public Nullable<double> kalan_tutar { get; set; }
    }
}
