//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class donemler
    {
        public int id { get; set; }
        public string Egitim_Kurumu { get; set; }
        public string Temel_Yenileme { get; set; }
        public string Donem { get; set; }
        public string Calisma_Yili { get; set; }
        public string Baslama_Yili { get; set; }
        public string Bitis_Yili { get; set; }
        public string Donem_Aciklama { get; set; }
    }
}
