//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doviz
    {
        public int id { get; set; }
        public string birimi { get; set; }
        public string simgesi { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<short> gunluk_kur_uyarisi { get; set; }
        public Nullable<decimal> alis_fiyati { get; set; }
        public Nullable<decimal> satis_fiyati { get; set; }
        public string ozel_kodu { get; set; }
        public Nullable<int> kur_hassasiyeti { get; set; }
        public string kucuk_birimi { get; set; }
        public string kucuk_simgesi { get; set; }
        public Nullable<short> para_orani { get; set; }
        public string not_1 { get; set; }
        public string not_2 { get; set; }
        public string kaydeden { get; set; }
        public string degistiren { get; set; }
        public Nullable<System.DateTime> degistirme_tarihi { get; set; }
    }
}
