//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class efaturanumaracontrol
    {
        public int EControlId { get; set; }
        public string EI_Scenario { get; set; }
        public string EI_No { get; set; }
        public string NumberType { get; set; }
    }
}
