//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class egitim_kurumu
    {
        public int id { get; set; }
        public string Kisa_Adi { get; set; }
        public string Unvan { get; set; }
        public string Yetkilisi { get; set; }
        public string Faaliyet_izin_No { get; set; }
        public string Telefon { get; set; }
        public string Faks { get; set; }
        public string Gsm { get; set; }
        public string Adres { get; set; }
        public string Kasa { get; set; }
        public string Logo { get; set; }
        public string Son_Sertifika_No { get; set; }
    }
}
