//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exceptions
    {
        public string CountryKey { get; set; }
        public string ExceptionCode { get; set; }
        public string ExceptionDesc { get; set; }
        public Nullable<byte> ExceptionType { get; set; }
    }
}
