//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fatura_hareket
    {
        public long id { get; set; }
        public long fatura_id { get; set; }
        public Nullable<long> stok_id { get; set; }
        public string stok_adi { get; set; }
        public Nullable<long> birim_id { get; set; }
        public Nullable<long> birim_2_id { get; set; }
        public Nullable<double> miktari { get; set; }
        public Nullable<double> miktari_2 { get; set; }
        public Nullable<double> kpb_fiyati { get; set; }
        public Nullable<double> kpb_kdv_haricfy { get; set; }
        public Nullable<double> kpb_ind_fiyat { get; set; }
        public Nullable<double> kpb_ara_tutar { get; set; }
        public Nullable<double> kpb_ind_tutar { get; set; }
        public Nullable<double> doviz_fiyati { get; set; }
        public Nullable<double> doviz_kdv_haricfy { get; set; }
        public Nullable<double> doviz_ind_fiyat { get; set; }
        public Nullable<double> doviz_ara_tutar { get; set; }
        public Nullable<double> doviz_ind_tutar { get; set; }
        public Nullable<int> doviz_birimi_id { get; set; }
        public Nullable<double> birim_carpani { get; set; }
        public Nullable<double> isonto_oran_cari { get; set; }
        public Nullable<double> isonto_tutar_cari { get; set; }
        public Nullable<double> isk_sntutar_cari { get; set; }
        public Nullable<double> iskonto_oran_1 { get; set; }
        public Nullable<double> iskonto_tutar_1 { get; set; }
        public Nullable<double> iskonto_sntutar_1 { get; set; }
        public Nullable<double> iskonto_oran_2 { get; set; }
        public Nullable<double> iskonto_tutar_2 { get; set; }
        public Nullable<double> iskonto_sntutar_2 { get; set; }
        public Nullable<double> iskonto_oran_3 { get; set; }
        public Nullable<double> iskonto_tutar_3 { get; set; }
        public Nullable<double> iskonto_sntutar_3 { get; set; }
        public Nullable<double> iskonto_oran_stok { get; set; }
        public Nullable<double> iskonto_tutar_stok { get; set; }
        public Nullable<double> iskonto_ozel { get; set; }
        public Nullable<double> iskonto_sntutar_ozel { get; set; }
        public Nullable<double> isk_ara_tutar { get; set; }
        public Nullable<double> otv_orani { get; set; }
        public Nullable<double> otv_tutari { get; set; }
        public Nullable<double> otvli_toplam { get; set; }
        public Nullable<double> kdv_orani { get; set; }
        public Nullable<double> kdv_tutari { get; set; }
        public Nullable<double> kpb_toplam_tutar { get; set; }
        public Nullable<double> kpb_kdvli_tutar { get; set; }
        public Nullable<double> doviz_toplam_tutar { get; set; }
        public Nullable<double> doviz_kdvli_tutar { get; set; }
        public Nullable<long> depo_id { get; set; }
        public string muh_kodu_genel { get; set; }
        public string ozel_kodu { get; set; }
        public string ek_bilgi_1 { get; set; }
        public string ek_bilgi_2 { get; set; }
        public string ek_bilgi_3 { get; set; }
        public string ek_bilgi_4 { get; set; }
        public Nullable<double> isk_sntutar_stok { get; set; }
        public string paz_personel { get; set; }
        public Nullable<long> paz_personel_id { get; set; }
        public Nullable<double> paz_urun_tutari { get; set; }
        public Nullable<double> paz_urun_orani { get; set; }
        public Nullable<double> paz_isc_orani { get; set; }
        public Nullable<double> paz_isc_tutari { get; set; }
        public string barkodu { get; set; }
        public Nullable<short> vade_gunu { get; set; }
        public Nullable<double> otv_birimi { get; set; }
        public Nullable<double> oiv_orani { get; set; }
        public Nullable<double> oiv_tutari { get; set; }
        public Nullable<long> hzm_id { get; set; }
        public string birimler { get; set; }
        public Nullable<short> kpb_doviz { get; set; }
        public Nullable<long> ana_stok_id { get; set; }
        public Nullable<double> kpb_fiyati_2 { get; set; }
        public Nullable<double> isk_tutar_cari_doviz { get; set; }
        public Nullable<double> isk_sntutar_cari_doviz { get; set; }
        public Nullable<double> isk_tutar_1_doviz { get; set; }
        public Nullable<double> isk_sntutar_1_doviz { get; set; }
        public Nullable<double> isk_tutar_2_doviz { get; set; }
        public Nullable<double> isk_sntutar_2_doviz { get; set; }
        public Nullable<double> isk_tutar_3_doviz { get; set; }
        public Nullable<double> isk_sntutar_3_doviz { get; set; }
        public Nullable<double> isk_tutar_stok_doviz { get; set; }
        public Nullable<double> isk_ozel_doviz { get; set; }
        public Nullable<double> isk_sntutar_ozel_doviz { get; set; }
        public Nullable<double> isk_sntutar_stok_doviz { get; set; }
        public Nullable<short> sip_teslim_2 { get; set; }
        public Nullable<short> asorti_hareket { get; set; }
        public Nullable<double> asorti_miktari { get; set; }
        public Nullable<short> kdv_durumu { get; set; }
        public Nullable<short> sira_no { get; set; }
        public Nullable<double> otv_tutari_doviz { get; set; }
        public Nullable<double> otvli_toplam_doviz { get; set; }
        public Nullable<double> paz_isc_tutari_doviz { get; set; }
        public Nullable<double> otv_birimi_doviz { get; set; }
        public Nullable<double> oiv_tutari_doviz { get; set; }
        public Nullable<double> paz_urun_tutari_doviz { get; set; }
        public Nullable<short> tevkifat_orani_1 { get; set; }
        public Nullable<short> tevkifat_orani_2 { get; set; }
        public string evrak_no { get; set; }
        public Nullable<double> doviz_alis { get; set; }
        public Nullable<double> doviz_satis { get; set; }
        public Nullable<short> kdv_85_kullan { get; set; }
        public Nullable<double> paz_urun_bf { get; set; }
        public Nullable<double> ek_maliyet_kpb { get; set; }
        public Nullable<short> seri_no_kullan { get; set; }
        public Nullable<double> bonus_orani { get; set; }
        public Nullable<double> bonus_tutari { get; set; }
        public Nullable<double> bonus_brfyt { get; set; }
        public string masraf_merkezi { get; set; }
        public Nullable<double> doviz_fiyati_2 { get; set; }
        public Nullable<double> iskonto_tutar_prm { get; set; }
        public Nullable<double> iskonto_sntutar_prm { get; set; }
        public Nullable<double> iskonto_tutar_prm_doviz { get; set; }
        public Nullable<double> iskonto_sntutar_prm_doviz { get; set; }
        public string istisna_kodu { get; set; }
        public Nullable<double> iskonto_tutar_bonus { get; set; }
        public Nullable<double> iskonto_sntutar_bonus { get; set; }
        public Nullable<double> iskonto_tutar_bonus_doviz { get; set; }
        public Nullable<double> iskonto_sntutar_bonus_doviz { get; set; }
        public string offline_guid { get; set; }
        public Nullable<short> silindi { get; set; }
        public string tevkifat_kodu { get; set; }
        public Nullable<double> tevkifat_sntutari_doviz { get; set; }
        public Nullable<double> tevkifat_sntutari_kpb { get; set; }
    }
}
