//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class grup
    {
        public long id { get; set; }
        public long g_id { get; set; }
        public string ismi { get; set; }
        public string aciklama { get; set; }
        public string modul { get; set; }
        public short webde_gorunsun { get; set; }
    }
}
