//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gunsonu_gelir
    {
        public int id { get; set; }
        public Nullable<double> nakit { get; set; }
        public Nullable<double> pos { get; set; }
        public string kaydeden { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public Nullable<short> silindi { get; set; }
    }
}
