//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class irsaliye
    {
        public long id { get; set; }
        public Nullable<short> irsaliye_durumu { get; set; }
        public Nullable<long> cari_id { get; set; }
        public string cari_kodu { get; set; }
        public string ticari_unvani { get; set; }
        public string adi_soyadi { get; set; }
        public string vergi_no { get; set; }
        public string vergi_dairesi { get; set; }
        public string tel_1 { get; set; }
        public string faks { get; set; }
        public string adresi { get; set; }
        public string ili { get; set; }
        public string ilcesi { get; set; }
        public string ozel_kodu { get; set; }
        public Nullable<short> kul_stok_fiyati { get; set; }
        public string irsaliye_no { get; set; }
        public System.DateTime tarihi { get; set; }
        public Nullable<System.DateTime> vadesi { get; set; }
        public Nullable<System.DateTime> fatura_tarihi { get; set; }
        public string grubu { get; set; }
        public string aciklama { get; set; }
        public Nullable<short> kdv_durumu { get; set; }
        public Nullable<double> kdv_orani { get; set; }
        public string ek_bilgi_1 { get; set; }
        public string ek_bilgi_2 { get; set; }
        public Nullable<short> isk_kul_cari { get; set; }
        public Nullable<double> isk_oran_cari { get; set; }
        public Nullable<double> isk_tutar_cari { get; set; }
        public Nullable<short> isk_kul_1 { get; set; }
        public Nullable<double> isk_oran_1 { get; set; }
        public Nullable<double> isk_tutar_1 { get; set; }
        public Nullable<short> isk_kul_2 { get; set; }
        public Nullable<double> isk_oran_2 { get; set; }
        public Nullable<double> isk_tutar_2 { get; set; }
        public Nullable<short> isk_kul_3 { get; set; }
        public Nullable<double> isk_oran_3 { get; set; }
        public Nullable<double> isk_tutar_3 { get; set; }
        public Nullable<short> isk_kul_stok { get; set; }
        public Nullable<double> isk_tutar_stok { get; set; }
        public Nullable<short> isk_kul_ozel { get; set; }
        public Nullable<double> isk_tutar_ozel { get; set; }
        public Nullable<short> isk_kul_alt { get; set; }
        public Nullable<double> isk_oran_alt { get; set; }
        public Nullable<double> isk_tutar_alt_1 { get; set; }
        public Nullable<double> isk_tutar_alt_2 { get; set; }
        public Nullable<short> cari_hareket_isle { get; set; }
        public Nullable<short> stok_hareket_isle { get; set; }
        public Nullable<short> doviz_kullan { get; set; }
        public string doviz_birimi { get; set; }
        public Nullable<short> kpb_doviz_cari { get; set; }
        public Nullable<short> dvz_hsile_stok { get; set; }
        public Nullable<short> dvz_hsile_cari { get; set; }
        public Nullable<short> paz_durumu { get; set; }
        public string paz_personel { get; set; }
        public Nullable<long> paz_personel_id { get; set; }
        public Nullable<double> paz_urun_tutari { get; set; }
        public Nullable<double> paz_urun_orani { get; set; }
        public Nullable<double> paz_isc_orani { get; set; }
        public Nullable<double> paz_isc_tutari { get; set; }
        public string sevk_adresi { get; set; }
        public string sevk_ili { get; set; }
        public string sevk_ilcesi { get; set; }
        public Nullable<System.DateTime> sevk_tarihi { get; set; }
        public Nullable<double> toplam_alt_kpb { get; set; }
        public Nullable<double> toplam_isk_kpb { get; set; }
        public Nullable<double> toplam_ara_kpb { get; set; }
        public Nullable<double> yuvarlama_kpb { get; set; }
        public Nullable<double> toplam_kdv_kpb { get; set; }
        public Nullable<double> toplam_genel_kpb { get; set; }
        public Nullable<double> miktar_1_toplam { get; set; }
        public Nullable<double> miktar_2_toplam { get; set; }
        public Nullable<double> toplam_alt_dvz { get; set; }
        public Nullable<double> toplam_isk_dvz { get; set; }
        public Nullable<double> toplam_ara_dvz { get; set; }
        public Nullable<double> yuvarlama_dvz { get; set; }
        public Nullable<double> toplam_kdv_dvz { get; set; }
        public Nullable<double> toplam_genel_dvz { get; set; }
        public Nullable<short> irsaliye_kesildi { get; set; }
        public Nullable<double> toplam_isk_stok { get; set; }
        public Nullable<double> toplam_isk_fat { get; set; }
        public Nullable<double> toplam_isk_yuzdesi { get; set; }
        public Nullable<System.DateTime> degistirme_tarihi { get; set; }
        public Nullable<long> kaydeden { get; set; }
        public Nullable<long> degistiren { get; set; }
        public Nullable<short> vade_durumu { get; set; }
        public Nullable<short> ortalama_vade { get; set; }
        public Nullable<short> faturalandi { get; set; }
        public Nullable<short> iptal { get; set; }
        public Nullable<short> silindi { get; set; }
        public string fatura_no { get; set; }
        public Nullable<long> bl_firsat_id { get; set; }
        public string aciklama_2 { get; set; }
        public Nullable<long> sube_id { get; set; }
        public string ulkesi { get; set; }
        public string sevk_ulkesi { get; set; }
        public string trs_kaynak_sube { get; set; }
        public string trs_kaynak_depo { get; set; }
        public string trs_kaynak_personel { get; set; }
        public string trs_hedef_sube { get; set; }
        public string trs_hedef_depo { get; set; }
        public string trs_hedef_personel { get; set; }
        public Nullable<short> trs_hedef_durumu { get; set; }
        public Nullable<System.DateTime> trs_hedef_tarihi { get; set; }
        public Nullable<short> gm_entegrasyon { get; set; }
        public Nullable<double> isk_tutar_cari_dvz { get; set; }
        public Nullable<double> isk_tutar_1_dvz { get; set; }
        public Nullable<double> isk_tutar_2_dvz { get; set; }
        public Nullable<double> isk_tutar_3_dvz { get; set; }
        public Nullable<double> isk_tutar_stok_dvz { get; set; }
        public Nullable<double> isk_tutar_ozel_dvz { get; set; }
        public Nullable<double> isk_tutar_alt_1_dvz { get; set; }
        public Nullable<double> isk_tutar_alt_2_dvz { get; set; }
        public Nullable<double> toplam_isk_stok_dvz { get; set; }
        public Nullable<double> toplam_isk_fat_dvz { get; set; }
        public Nullable<double> paz_urun_tutari_dvz { get; set; }
        public Nullable<double> paz_isc_tutari_dvz { get; set; }
        public Nullable<System.DateTime> tarihi_2 { get; set; }
        public Nullable<short> offline_durum { get; set; }
        public string source_app { get; set; }
        public Nullable<short> yuvarlama_kullan { get; set; }
        public string cep_tel { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public string kargo_firmasi { get; set; }
        public string kargo_no { get; set; }
        public Nullable<long> sevk_id { get; set; }
        public string sevk_tanimi { get; set; }
        public string sevk_yetkilisi { get; set; }
        public string sevk_tel { get; set; }
        public Nullable<short> faturalanacak { get; set; }
        public Nullable<short> e_fatura_e_ticaret { get; set; }
        public string e_fatura_site_adi { get; set; }
        public string e_fatura_tfirma_vkn { get; set; }
        public string e_fatura_tfirma_adi { get; set; }
        public string offline_guid { get; set; }
    }
}
