//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class irsaliye_hareket
    {
        public long id { get; set; }
        public long irsaliye_id { get; set; }
        public Nullable<long> stok_id { get; set; }
        public string stok_kodu { get; set; }
        public string stok_adi { get; set; }
        public string birimi { get; set; }
        public string birimi_2 { get; set; }
        public Nullable<double> miktari { get; set; }
        public Nullable<double> miktari_2 { get; set; }
        public Nullable<double> kpb_fiyati { get; set; }
        public Nullable<double> kpb_kdv_haricfy { get; set; }
        public Nullable<double> kpb_ind_fiyat { get; set; }
        public Nullable<double> kpb_ara_tutar { get; set; }
        public Nullable<double> kpb_ind_tutar { get; set; }
        public Nullable<double> dvz_fiyati { get; set; }
        public Nullable<double> dvz_kdv_haricfy { get; set; }
        public Nullable<double> dvz_ind_fiyat { get; set; }
        public Nullable<double> dvz_ara_tutar { get; set; }
        public Nullable<double> dvz_ind_tutar { get; set; }
        public string doviz_birimi_id { get; set; }
        public Nullable<double> birim_carpani { get; set; }
        public Nullable<double> isk_oran_cari { get; set; }
        public Nullable<double> isk_tutar_cari { get; set; }
        public Nullable<double> isk_sntutar_cari { get; set; }
        public Nullable<double> isk_oran_1 { get; set; }
        public Nullable<double> isk_tutar_1 { get; set; }
        public Nullable<double> isk_sntutar_1 { get; set; }
        public Nullable<double> isk_oran_2 { get; set; }
        public Nullable<double> isk_tutar_2 { get; set; }
        public Nullable<double> isk_sntutar_2 { get; set; }
        public Nullable<double> isk_oran_3 { get; set; }
        public Nullable<double> isk_tutar_3 { get; set; }
        public Nullable<double> isk_sntutar_3 { get; set; }
        public Nullable<double> isk_oran_stok { get; set; }
        public Nullable<double> isk_tutar_stok { get; set; }
        public Nullable<double> isk_ozel { get; set; }
        public Nullable<double> isk_sntutar_ozel { get; set; }
        public Nullable<double> isk_ara_tutar { get; set; }
        public Nullable<double> kdv_orani { get; set; }
        public Nullable<double> kdv_tutari { get; set; }
        public Nullable<double> kpb_toplam_tutar { get; set; }
        public Nullable<double> kpb_kdvli_tutar { get; set; }
        public Nullable<double> dvz_toplam_tutar { get; set; }
        public Nullable<double> dvz_kdvli_tutar { get; set; }
        public Nullable<long> depo_id { get; set; }
        public string muh_kodu_genel { get; set; }
        public string ozel_kodu { get; set; }
        public string ek_bilgi_1 { get; set; }
        public string ek_bilgi_2 { get; set; }
        public string ek_bilgi_3 { get; set; }
        public string ek_bilgi_4 { get; set; }
        public Nullable<double> isk_sntutar_stok { get; set; }
        public string paz_personel { get; set; }
        public Nullable<long> paz_pers_id { get; set; }
        public Nullable<double> paz_urun_tutari { get; set; }
        public Nullable<double> paz_urun_orani { get; set; }
        public Nullable<double> paz_isc_orani { get; set; }
        public Nullable<double> paz_isc_tutari { get; set; }
        public string barkodu { get; set; }
        public Nullable<short> vade_gunu { get; set; }
        public Nullable<long> hzm_id { get; set; }
        public string birimler { get; set; }
        public Nullable<short> kpbdvz { get; set; }
        public string ana_stok_kodu { get; set; }
        public Nullable<short> sip_teslim_2 { get; set; }
        public Nullable<short> asorti_hrk { get; set; }
        public Nullable<double> asorti_miktari { get; set; }
        public Nullable<short> kdv_durumu { get; set; }
        public Nullable<short> sira_no { get; set; }
        public Nullable<double> isk_tutar_cari_dvz { get; set; }
        public Nullable<double> isk_sntutar_cari_dvz { get; set; }
        public Nullable<double> isk_tutar_1_dvz { get; set; }
        public Nullable<double> isk_sntutar_1_dvz { get; set; }
        public Nullable<double> isk_tutar_2_dvz { get; set; }
        public Nullable<double> isk_sntutar_2_dvz { get; set; }
        public Nullable<double> isk_tutar_3_dvz { get; set; }
        public Nullable<double> isk_sntutar_3_dvz { get; set; }
        public Nullable<double> isk_tutar_stok_dvz { get; set; }
        public Nullable<double> isk_sntutar_stok_dvz { get; set; }
        public Nullable<double> isk_ozel_dvz { get; set; }
        public Nullable<double> isk_sntutar_ozel_dvz { get; set; }
        public Nullable<double> paz_isc_tutari_dvz { get; set; }
        public Nullable<double> paz_urun_tutari_dvz { get; set; }
        public string evrak_no { get; set; }
        public Nullable<double> doviz_alis { get; set; }
        public Nullable<double> doviz_satis { get; set; }
        public Nullable<double> paz_urun_bf { get; set; }
        public Nullable<double> kpb_fiyati_2 { get; set; }
        public Nullable<short> seri_no_kullan { get; set; }
        public Nullable<double> dvz_fiyati_2 { get; set; }
        public string offline_guid { get; set; }
        public string stok_adi_yd { get; set; }
    }
}
