//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kartli_puan_kampanya
    {
        public long id { get; set; }
        public string kampanya_adi { get; set; }
        public Nullable<double> satis_tutari { get; set; }
        public string kampanya_sarti { get; set; }
        public string yuklenecek_para_puan_turu { get; set; }
        public Nullable<double> yuklenecek_para_puan_nakit { get; set; }
        public Nullable<double> yuklenecek_para_puan_yuzde { get; set; }
        public Nullable<double> maksimum_para_puan { get; set; }
        public string aciklama { get; set; }
        public Nullable<System.DateTime> kampanya_baslangic_tarihi { get; set; }
        public Nullable<System.DateTime> kampanya_bitis_tarihi { get; set; }
        public Nullable<System.DateTime> para_puan_baslangic_tarihi { get; set; }
        public Nullable<System.DateTime> para_puan_bitis_tarihi { get; set; }
        public Nullable<int> kaydeden { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public Nullable<int> degistiren { get; set; }
        public Nullable<System.DateTime> degistirme_tarihi { get; set; }
        public Nullable<int> silindi { get; set; }
    }
}
