//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kasa_hareket
    {
        public int id { get; set; }
        public Nullable<System.DateTime> tarihi { get; set; }
        public string evrak_no { get; set; }
        public string ozel_kodu { get; set; }
        public string grubu { get; set; }
        public string ara_grubu { get; set; }
        public string alt_grubu { get; set; }
        public Nullable<short> doviz_kullan { get; set; }
        public Nullable<int> doviz_birimi_id { get; set; }
        public Nullable<double> doviz_alis { get; set; }
        public Nullable<double> doviz_satis { get; set; }
        public Nullable<short> kpb_doviz { get; set; }
        public int kasa_id { get; set; }
        public string aciklama { get; set; }
        public string banka_adi { get; set; }
        public string muh_kodu { get; set; }
        public Nullable<long> cari_hareket_id { get; set; }
        public Nullable<long> cari_stok_id { get; set; }
        public Nullable<long> transfer_id { get; set; }
        public Nullable<double> kpb_gelen_tutar { get; set; }
        public Nullable<double> kpb_giden_tutar { get; set; }
        public Nullable<double> dvz_gelen_tutar { get; set; }
        public Nullable<double> dvz_giden_tutar { get; set; }
        public Nullable<long> kaydeden { get; set; }
        public Nullable<long> degistiren { get; set; }
        public Nullable<System.DateTime> degistirme_tarihi { get; set; }
        public Nullable<short> silindi { get; set; }
        public Nullable<long> BLBNHSKODU { get; set; }
        public Nullable<short> gm_entegrasyon { get; set; }
        public Nullable<long> cari_id { get; set; }
        public Nullable<long> kulup_buton_id { get; set; }
        public Nullable<short> kampanya_kullandi { get; set; }
        public Nullable<System.DateTime> tarihi_2 { get; set; }
        public Nullable<short> offline_durum { get; set; }
        public string bag_no { get; set; }
        public string source_app { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public string edf_belge_turu { get; set; }
        public string edf_belge_turu_dig { get; set; }
    }
}
