//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kasa
    {
        public int id { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public string yetkilisi { get; set; }
        public string kasa_adi { get; set; }
        public string ozel_kodu { get; set; }
        public string aciklama_1 { get; set; }
        public string aciklama_2 { get; set; }
        public string aciklama_3 { get; set; }
        public string muh_kodu { get; set; }
        public string kaydeden { get; set; }
        public string degistiren { get; set; }
        public Nullable<System.DateTime> degistirme_tarihi { get; set; }
        public string terminaller { get; set; }
        public string kullanicilar { get; set; }
        public string sube_kodu { get; set; }
        public Nullable<short> aktif { get; set; }
        public Nullable<short> silindi { get; set; }
    }
}
