//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kisayol_butonlar
    {
        public int id { get; set; }
        public string turu { get; set; }
        public string baslik { get; set; }
        public string ismi { get; set; }
        public string icon { get; set; }
        public Nullable<int> sutun { get; set; }
        public int siralama { get; set; }
    }
}
