//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kulup_giris_telefon_listesi
    {
        public long id { get; set; }
        public string cep_telefon { get; set; }
        public Nullable<int> giris_sayisi { get; set; }
        public Nullable<System.DateTime> islem_tarihi { get; set; }
    }
}
