//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kulup_butonlar
    {
        public int id { get; set; }
        public string ismi { get; set; }
        public double fiyati { get; set; }
        public string para_birimi { get; set; }
        public int varsayilan_kisi_sayisi { get; set; }
        public Nullable<long> menu_id { get; set; }
        public int siralama { get; set; }
        public bool durum { get; set; }
        public Nullable<bool> silindi { get; set; }
    }
}
