//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kulup_girisler
    {
        public long id { get; set; }
        public Nullable<long> cari_id { get; set; }
        public string kart_numarasi { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> buton_id { get; set; }
        public Nullable<int> kisi_sayisi { get; set; }
        public Nullable<double> fiyati { get; set; }
        public string para_birimi { get; set; }
        public Nullable<int> silindi { get; set; }
        public Nullable<long> kaydeden { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public Nullable<long> degistiren { get; set; }
        public Nullable<System.DateTime> degistirme_tarihi { get; set; }
    }
}
