//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kursiyer_dersler
    {
        public int id { get; set; }
        public string ders_adi { get; set; }
        public Nullable<int> g_id { get; set; }
        public string modul { get; set; }
        public Nullable<short> webde_gorunsun { get; set; }
        public Nullable<int> ders_silindi { get; set; }
    }
}
