//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kursiyer_devamsizlik
    {
        public int id { get; set; }
        public Nullable<int> kursiyer_id { get; set; }
        public string devamsizlik_tarihi { get; set; }
        public string devamsizlik_kodu { get; set; }
        public string devamsizlik_saat { get; set; }
        public string egitmen { get; set; }
        public string ders_adi { get; set; }
        public Nullable<int> silindi { get; set; }
    }
}
