//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kursiyer_kardes_bilgileri
    {
        public int kardes_id { get; set; }
        public Nullable<int> kursiyer_id { get; set; }
        public string kardes_adi_soyadi { get; set; }
        public string kardes_dogum_tarihi { get; set; }
        public string kardes_dogum_yeri { get; set; }
        public string kardes_uyrugu { get; set; }
        public string kardes_adresi { get; set; }
    }
}
