//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kursiyer_evrak
    {
        public int id { get; set; }
        public Nullable<int> kursiyer_id { get; set; }
        public Nullable<int> temel_nufus_fotokopi { get; set; }
        public Nullable<int> temel_6_adet_fotograf { get; set; }
        public Nullable<int> temel_ikametgah { get; set; }
        public Nullable<int> temel_diploma { get; set; }
        public Nullable<int> temel_vukuatli_kayit { get; set; }
        public Nullable<int> temel_sabika_kaydi { get; set; }
        public Nullable<int> temel_mavi_telli_dosya { get; set; }
        public Nullable<int> temel_saglik_raporlari { get; set; }
        public Nullable<int> yenileme_nufus_fotokopisi { get; set; }
        public Nullable<int> yenileme_4_adet_fotograf { get; set; }
        public Nullable<int> yenileme_ikametgah { get; set; }
        public Nullable<int> yenileme_diploma { get; set; }
        public Nullable<int> yenileme_vukuatli_kayit { get; set; }
        public Nullable<int> yenileme_sabika_kaydi { get; set; }
        public Nullable<int> yenileme_mavi_telli_dosya { get; set; }
        public Nullable<int> yenileme_sertifika_fotokopisi { get; set; }
        public Nullable<int> yenileme_saglik_raporu { get; set; }
        public Nullable<int> silindi { get; set; }
    }
}
