//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kursiyer_egitim_bilgileri
    {
        public int id { get; set; }
        public Nullable<int> kursiyer_id { get; set; }
        public string kayit_egitim_tercihi { get; set; }
        public string kayit_egitim_turu { get; set; }
        public string kayit_donemi { get; set; }
        public string kayit_egitim_baslangic_tarihi { get; set; }
        public string kayit_egitim_bitis_tarihi { get; set; }
        public string kimlik_belge_no { get; set; }
        public string kimlik_silah_durumu { get; set; }
        public string kimlik_kan_grubu { get; set; }
        public string kimlik_yenileme_durumu { get; set; }
        public string kimlik_verilis_tarihi { get; set; }
        public string kimlik_gecerlilik_suresi { get; set; }
        public string devam_genel_devamsizlik { get; set; }
        public string devam_mazaretsiz { get; set; }
        public string devam_mazeretli { get; set; }
        public string sertifika_belge_no { get; set; }
        public string sertifika_duzenleme_tarihi { get; set; }
        public string sertifika_gecerlilik_suresi { get; set; }
        public string egitim_durumu { get; set; }
        public string gece_gunduz { get; set; }
    }
}
