//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kursiyer_evrak_kontrol
    {
        public int id { get; set; }
        public Nullable<int> cari_id { get; set; }
        public Nullable<int> evrak_id { get; set; }
        public Nullable<int> durumu { get; set; }
        public string modul { get; set; }
        public Nullable<short> silindi { get; set; }
    }
}
