//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kursiyer_ders_programi
    {
        public int id { get; set; }
        public string egitim_kurumu { get; set; }
        public string egitim_turu { get; set; }
        public string kurs_donemi { get; set; }
        public string egitim_tercihi { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string ders_1_adi { get; set; }
        public string ders_2_adi { get; set; }
        public string ders_3_adi { get; set; }
        public string ders_4_adi { get; set; }
        public string ders_5_adi { get; set; }
        public string ders_6_adi { get; set; }
        public string ders_7_adi { get; set; }
        public string ders_8_adi { get; set; }
        public string ders_9_adi { get; set; }
        public string ders_10_adi { get; set; }
        public string ders_1_egitimci { get; set; }
        public string ders_2_egitimci { get; set; }
        public string ders_3_egitimci { get; set; }
        public string ders_4_egitimci { get; set; }
        public string ders_5_egitimci { get; set; }
        public string ders_6_egitimci { get; set; }
        public string ders_7_egitimci { get; set; }
        public string ders_8_egitimci { get; set; }
        public string ders_9_egitimci { get; set; }
        public string ders_10_egitimci { get; set; }
        public Nullable<int> silindi { get; set; }
    }
}
