//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kursiyer
    {
        public int id { get; set; }
        public string kursiyer_kodu { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string adresi { get; set; }
        public string ulkesi { get; set; }
        public string ili { get; set; }
        public string ilcesi { get; set; }
        public string grubu { get; set; }
        public string ara_grubu { get; set; }
        public string alt_grubu { get; set; }
        public string evraklar { get; set; }
        public string telefon_1 { get; set; }
        public string telefon_2 { get; set; }
        public string ev_telefonu { get; set; }
        public string cep_telefonu { get; set; }
        public string faks { get; set; }
        public string ozel_kodu_1 { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public Nullable<System.DateTime> ozel_tarih { get; set; }
        public string tc_kimlik_no { get; set; }
        public Nullable<short> durumu { get; set; }
        public Nullable<short> cuzdan_turu { get; set; }
        public string cuzdan_seri { get; set; }
        public string seri_no { get; set; }
        public string nufus_tc_kimlik_no { get; set; }
        public string baba_adi { get; set; }
        public string ana_adi { get; set; }
        public string dogum_yeri { get; set; }
        public string dogum_tarihi { get; set; }
        public Nullable<short> medeni_hali { get; set; }
        public string uyrugu { get; set; }
        public Nullable<short> cinsiyeti { get; set; }
        public string dini { get; set; }
        public string nufus_ili { get; set; }
        public string nufus_ilcesi { get; set; }
        public string mahalle_koy { get; set; }
        public string cilt_no { get; set; }
        public string aile_sira_no { get; set; }
        public string sira_no { get; set; }
        public string nufus_dairesi { get; set; }
        public string verilis_nedeni { get; set; }
        public Nullable<short> kan_grubu { get; set; }
        public string askerlik_hizmeti { get; set; }
        public string askerlik_baslangic_tarihi { get; set; }
        public string askerlik_bitis_tarihi { get; set; }
        public string nufus_onaylayan_adi { get; set; }
        public string nufus_onaylayan_soyadi { get; set; }
        public string nufus_onaylayan_gorevi { get; set; }
        public string nufus_onaylayan_tarihi { get; set; }
        public string nufus_bilgileri_ek_bilgi { get; set; }
        public string kredi_karti_1 { get; set; }
        public string kredi_karti_2 { get; set; }
        public string icq { get; set; }
        public string e_posta { get; set; }
        public string web { get; set; }
        public string not_1 { get; set; }
        public string not_2 { get; set; }
        public string not_3 { get; set; }
        public string kullanici_adi { get; set; }
        public string sifre { get; set; }
        public string banka_1_banka_adi { get; set; }
        public string banka_1_sube_adi { get; set; }
        public string banka_1_sube_kodu { get; set; }
        public string banka_1_hesap_no { get; set; }
        public string banka_1_iban_no { get; set; }
        public string banka_1_swift_kodu { get; set; }
        public string banka_2_banka_adi { get; set; }
        public string banka_2_sube_adi { get; set; }
        public string banka_2_sube_kodu { get; set; }
        public string banka_2_hesap_no { get; set; }
        public string banka_2_iban_no { get; set; }
        public string banka_2_swift_kodu { get; set; }
        public string resim_yolu { get; set; }
        public Nullable<short> silindi { get; set; }
        public string kurs_ucreti { get; set; }
        public string harc_ucreti { get; set; }
    }
}
