//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kursiyer_aile_bilgileri
    {
        public int id { get; set; }
        public Nullable<int> kursiyer_id { get; set; }
        public string oturdugu_yer { get; set; }
        public string baba_adi_soyadi { get; set; }
        public string baba_dogum_tarihi { get; set; }
        public string baba_dogum_yeri { get; set; }
        public string baba_uyrugu { get; set; }
        public string baba_adres { get; set; }
        public string anne_adi_soyadi { get; set; }
        public string anne_dogum_tarihi { get; set; }
        public string anne_dogum_yeri { get; set; }
        public string anne_uyrugu { get; set; }
        public string anne_adres { get; set; }
        public string es_adi_soyadi { get; set; }
        public string es_dogum_tarihi { get; set; }
        public string es_dogum_yeri { get; set; }
        public string es_uyrugu { get; set; }
        public string es_adres { get; set; }
        public Nullable<int> kardes_id { get; set; }
        public string okul_adi { get; set; }
        public string okul_baslangic_tarihi { get; set; }
        public string okul_bitis_tarihi { get; set; }
        public string calistigi_is_cesidi { get; set; }
        public string is_baslama_tarihi { get; set; }
        public string is_bitis_tarihi { get; set; }
        public string is_veren_adresi { get; set; }
        public string is_ayrilma_sebebi { get; set; }
    }
}
