//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kursiyer_sinav_bilgileri
    {
        public int id { get; set; }
        public Nullable<int> kursiyer_id { get; set; }
        public string birinci_check_box { get; set; }
        public string birinci_sinav_emn_donem { get; set; }
        public string birinci_sinav_harci { get; set; }
        public string birinci_sinav_harci_2 { get; set; }
        public string birinci_sinav_turu { get; set; }
        public string birinci_silahsiz_yazili { get; set; }
        public string birinci_silahli_yazili { get; set; }
        public string birinci_puan { get; set; }
        public string birinci_sonuc { get; set; }
        public string ikinci_check_box { get; set; }
        public string ikinci_sinav_emn_donem { get; set; }
        public string ikinci_sinav_harci { get; set; }
        public string ikinci_sinav_harci_2 { get; set; }
        public string ikinci_sinav_turu { get; set; }
        public string ikinci_silahsiz_yazili { get; set; }
        public string ikinci_silahli_yazili { get; set; }
        public string ikinci_puan { get; set; }
        public string ikinci_sonuc { get; set; }
        public string ucuncu_check_box { get; set; }
        public string ucuncu_sinav_emn_donem { get; set; }
        public string ucuncu_sinav_harci { get; set; }
        public string ucuncu_sinav_harci_2 { get; set; }
        public string ucuncu_sinav_turu { get; set; }
        public string ucuncu_silahsiz_yazili { get; set; }
        public string ucuncu_silahli_yazili { get; set; }
        public string ucuncu_puan { get; set; }
        public string ucuncu_sonuc { get; set; }
        public string dorduncu_check_box { get; set; }
        public string dorduncu_sinav_emn_donem { get; set; }
        public string dorduncu_sinav_harci { get; set; }
        public string dorduncu_sinav_harci_2 { get; set; }
        public string dorduncu_sinav_turu { get; set; }
        public string dorduncu_silahsiz_yazili { get; set; }
        public string dorduncu_silahli_yazili { get; set; }
        public string dorduncu_puan { get; set; }
        public string dorduncu_sonuc { get; set; }
        public string egitim_atis_mesafesi { get; set; }
        public string egitim_mermi_adedi { get; set; }
        public string egitim_puan { get; set; }
        public string sinav_atis_mesafesi { get; set; }
        public string sinav_mermi_adedi { get; set; }
        public string belge_no { get; set; }
        public string belge_gecerlilik_suresi { get; set; }
        public string sinav_tarihi { get; set; }
        public string yazili_sinav_okul_adi { get; set; }
        public string yazili_sinav_okul_adresi { get; set; }
        public string yazili_sinav_salonu { get; set; }
        public string yazili_sinav_tarihi_saati { get; set; }
        public string atis_sinav_yeri { get; set; }
        public string atis_sinav_tarihi_saati { get; set; }
        public string son_emniyet_sinav_no { get; set; }
        public Nullable<int> silindi { get; set; }
    }
}
