//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class masa
    {
        public long id { get; set; }
        public string masa_adi { get; set; }
        public string aciklama { get; set; }
        public Nullable<long> masa_grubu_id { get; set; }
        public Nullable<int> kac_kisilik { get; set; }
        public Nullable<int> durumu { get; set; }
        public Nullable<int> sol { get; set; }
        public Nullable<int> ust { get; set; }
        public Nullable<long> rezervasyon_id { get; set; }
        public string varsayilan_tarife { get; set; }
        public Nullable<short> gizli { get; set; }
        public Nullable<long> sube_id { get; set; }
        public string offline_id { get; set; }
        public Nullable<int> garson_cagri_durum { get; set; }
        public string garson_cagri_id { get; set; }
        public Nullable<short> vip { get; set; }
        public Nullable<System.DateTime> masa_acilis { get; set; }
        public Nullable<int> masa_ekran_durumu { get; set; }
    }
}
