//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sirketEntities1 : DbContext
    {
        public sirketEntities1()
            : base("name=sirketEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adisyon_fis> adisyon_fis { get; set; }
        public virtual DbSet<adisyon_hareket> adisyon_hareket { get; set; }
        public virtual DbSet<adisyon_hareket_yazdirma> adisyon_hareket_yazdirma { get; set; }
        public virtual DbSet<adisyon_mutfak_yazdirma> adisyon_mutfak_yazdirma { get; set; }
        public virtual DbSet<adisyon_odeme> adisyon_odeme { get; set; }
        public virtual DbSet<adisyon_stok_detay> adisyon_stok_detay { get; set; }
        public virtual DbSet<ayar> ayar { get; set; }
        public virtual DbSet<banka_adi> banka_adi { get; set; }
        public virtual DbSet<banka_cek_senet> banka_cek_senet { get; set; }
        public virtual DbSet<banka_hareket> banka_hareket { get; set; }
        public virtual DbSet<banka_hesap> banka_hesap { get; set; }
        public virtual DbSet<banka_kk_detay> banka_kk_detay { get; set; }
        public virtual DbSet<banka_pos_detay> banka_pos_detay { get; set; }
        public virtual DbSet<basit_uretim> basit_uretim { get; set; }
        public virtual DbSet<bekleme_listesi> bekleme_listesi { get; set; }
        public virtual DbSet<cari> cari { get; set; }
        public virtual DbSet<cari_hareket> cari_hareket { get; set; }
        public virtual DbSet<cari_hareket_onceki> cari_hareket_onceki { get; set; }
        public virtual DbSet<cari_izinler> cari_izinler { get; set; }
        public virtual DbSet<cari_notlar> cari_notlar { get; set; }
        public virtual DbSet<cari_servis_bilgiler> cari_servis_bilgiler { get; set; }
        public virtual DbSet<cari_yeni> cari_yeni { get; set; }
        public virtual DbSet<cari_yetkililer> cari_yetkililer { get; set; }
        public virtual DbSet<cek_senet> cek_senet { get; set; }
        public virtual DbSet<depo> depo { get; set; }
        public virtual DbSet<donemler> donemler { get; set; }
        public virtual DbSet<doviz> doviz { get; set; }
        public virtual DbSet<ekranlar> ekranlar { get; set; }
        public virtual DbSet<exceptions> exceptions { get; set; }
        public virtual DbSet<fatura> fatura { get; set; }
        public virtual DbSet<fatura_hareket> fatura_hareket { get; set; }
        public virtual DbSet<grup> grup { get; set; }
        public virtual DbSet<gun_sonu> gun_sonu { get; set; }
        public virtual DbSet<gunsonu_gelir> gunsonu_gelir { get; set; }
        public virtual DbSet<gunsonu_stok> gunsonu_stok { get; set; }
        public virtual DbSet<gunsonu_stok_hareket> gunsonu_stok_hareket { get; set; }
        public virtual DbSet<irsaliye> irsaliye { get; set; }
        public virtual DbSet<irsaliye_hareket> irsaliye_hareket { get; set; }
        public virtual DbSet<kartli_puan_kampanya> kartli_puan_kampanya { get; set; }
        public virtual DbSet<kasa> kasa { get; set; }
        public virtual DbSet<kasa_hareket> kasa_hareket { get; set; }
        public virtual DbSet<kisayol_butonlar> kisayol_butonlar { get; set; }
        public virtual DbSet<kulup_butonlar> kulup_butonlar { get; set; }
        public virtual DbSet<kulup_giris_telefon_listesi> kulup_giris_telefon_listesi { get; set; }
        public virtual DbSet<kulup_girisler> kulup_girisler { get; set; }
        public virtual DbSet<kursiyer> kursiyer { get; set; }
        public virtual DbSet<kursiyer_aile_bilgileri> kursiyer_aile_bilgileri { get; set; }
        public virtual DbSet<kursiyer_ders_programi> kursiyer_ders_programi { get; set; }
        public virtual DbSet<kursiyer_dersler> kursiyer_dersler { get; set; }
        public virtual DbSet<kursiyer_devamsizlik> kursiyer_devamsizlik { get; set; }
        public virtual DbSet<kursiyer_egitim_bilgileri> kursiyer_egitim_bilgileri { get; set; }
        public virtual DbSet<kursiyer_egitimciler> kursiyer_egitimciler { get; set; }
        public virtual DbSet<kursiyer_evrak> kursiyer_evrak { get; set; }
        public virtual DbSet<kursiyer_evrak_kontrol> kursiyer_evrak_kontrol { get; set; }
        public virtual DbSet<kursiyer_hareket> kursiyer_hareket { get; set; }
        public virtual DbSet<kursiyer_kardes_bilgileri> kursiyer_kardes_bilgileri { get; set; }
        public virtual DbSet<kursiyer_sinav_bilgileri> kursiyer_sinav_bilgileri { get; set; }
        public virtual DbSet<masa> masa { get; set; }
        public virtual DbSet<odemeler> odemeler { get; set; }
        public virtual DbSet<personel_evrak> personel_evrak { get; set; }
        public virtual DbSet<personel_proje_atanmasi> personel_proje_atanmasi { get; set; }
        public virtual DbSet<personel_urunler> personel_urunler { get; set; }
        public virtual DbSet<shift_islemleri> shift_islemleri { get; set; }
        public virtual DbSet<stok_bagli_stok> stok_bagli_stok { get; set; }
        public virtual DbSet<stok_birimler> stok_birimler { get; set; }
        public virtual DbSet<stok_ekranlar> stok_ekranlar { get; set; }
        public virtual DbSet<stok_fiyatlar> stok_fiyatlar { get; set; }
        public virtual DbSet<stok_hareket> stok_hareket { get; set; }
        public virtual DbSet<stok_menuler> stok_menuler { get; set; }
        public virtual DbSet<stok_menuler_hareket> stok_menuler_hareket { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<taxTypes> taxTypes { get; set; }
        public virtual DbSet<teklif> teklif { get; set; }
        public virtual DbSet<teklif_hareket> teklif_hareket { get; set; }
        public virtual DbSet<tevkifat> tevkifat { get; set; }
        public virtual DbSet<turnike> turnike { get; set; }
        public virtual DbSet<turnike_cari_durumlari> turnike_cari_durumlari { get; set; }
        public virtual DbSet<turnike_hareketler> turnike_hareketler { get; set; }
        public virtual DbSet<turnike_yetkililer> turnike_yetkililer { get; set; }
        public virtual DbSet<useful_life_codes> useful_life_codes { get; set; }
        public virtual DbSet<yazili_sinav_bilgileri> yazili_sinav_bilgileri { get; set; }
        public virtual DbSet<adisyon_buton> adisyon_buton { get; set; }
        public virtual DbSet<efaturadurum> efaturadurum { get; set; }
        public virtual DbSet<efaturanumaracontrol> efaturanumaracontrol { get; set; }
        public virtual DbSet<egitim_kurumu> egitim_kurumu { get; set; }
        public virtual DbSet<EI_Labels> EI_Labels { get; set; }
        public virtual DbSet<kursiyer_evraklar> kursiyer_evraklar { get; set; }
        public virtual DbSet<son_eklenenler> son_eklenenler { get; set; }
        public virtual DbSet<stok> stok { get; set; }
    }
}
