//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class odemeler
    {
        public long id { get; set; }
        public long cari_id { get; set; }
        public int kasa_id { get; set; }
        public short turu { get; set; }
        public string baslik { get; set; }
        public System.DateTime tarih { get; set; }
        public double tutar { get; set; }
        public string ozel_kodu { get; set; }
        public string aciklama_1 { get; set; }
        public string aciklama_2 { get; set; }
        public string aciklama_3 { get; set; }
        public Nullable<short> tamamlandi { get; set; }
        public short silindi { get; set; }
        public long kaydeden { get; set; }
        public System.DateTime kayit_tarihi { get; set; }
        public Nullable<long> degistiren { get; set; }
        public Nullable<System.DateTime> degistirme_tarihi { get; set; }
    }
}
