//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel_proje_atanmasi
    {
        public int id { get; set; }
        public Nullable<int> cari_id { get; set; }
        public string cari_kodu { get; set; }
        public string ticari_unvani { get; set; }
        public string calistigi_bolum { get; set; }
        public string proje_baslangic_tarihi { get; set; }
        public string proje_bitis_tarihi { get; set; }
        public string ssk_baslangic_tarihi { get; set; }
        public string personel_sozlesme_tarihi { get; set; }
        public string aciklama { get; set; }
        public Nullable<short> silindi { get; set; }
    }
}
