//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel_evrak
    {
        public int id { get; set; }
        public Nullable<int> personel_id { get; set; }
        public Nullable<int> nufus_cuzdani_4_foto { get; set; }
        public Nullable<int> ozel_guvenlik_kimligi { get; set; }
        public Nullable<int> ozel_guvenlik_sertifikası { get; set; }
        public Nullable<int> diploma { get; set; }
        public Nullable<int> ikametgah_illmuhaberi { get; set; }
        public Nullable<int> vukuatli_nufus_kaydi { get; set; }
        public Nullable<int> terhis_belgesi { get; set; }
        public Nullable<int> sabika_kaydi { get; set; }
        public Nullable<int> saglik_raporu { get; set; }
        public Nullable<int> fotograf_verikaslik { get; set; }
        public Nullable<int> telli_dosya_mavi { get; set; }
        public Nullable<int> banka_no { get; set; }
    }
}
