//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel_urunler
    {
        public int id { get; set; }
        public Nullable<int> cari_id { get; set; }
        public string gomlek_bedeni { get; set; }
        public Nullable<int> gomlek_adedi { get; set; }
        public string kazak_bedeni { get; set; }
        public Nullable<int> kazak_adedi { get; set; }
        public string mont_bedeni { get; set; }
        public Nullable<int> mont_adedi { get; set; }
        public string pantolon_bedeni { get; set; }
        public Nullable<int> pantolon_adedi { get; set; }
        public Nullable<int> ayakkabi_numarasi { get; set; }
        public Nullable<int> ayakkabi_adedi { get; set; }
        public Nullable<int> kravat_adedi { get; set; }
        public Nullable<int> kemer_adedi { get; set; }
        public Nullable<int> apolet_adedi { get; set; }
        public Nullable<int> arma_adedi { get; set; }
        public Nullable<int> kelepce_adedi { get; set; }
        public Nullable<int> jop_adedi { get; set; }
        public Nullable<System.DateTime> urun_ekleme_tarihi { get; set; }
        public Nullable<System.DateTime> urun_duzenleme_tarihi { get; set; }
        public Nullable<short> urun_durumu { get; set; }
        public Nullable<short> cinsiyeti { get; set; }
    }
}
