//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shift_islemleri
    {
        public long id { get; set; }
        public string hesap { get; set; }
        public Nullable<long> garson_id { get; set; }
        public Nullable<double> nakit_tutar { get; set; }
        public Nullable<double> pos_tutar { get; set; }
        public Nullable<long> sube_id { get; set; }
        public Nullable<System.DateTime> tarihi { get; set; }
        public Nullable<System.DateTime> restaurant_shift_tarihi { get; set; }
    }
}
