//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stok
    {
        public long id { get; set; }
        public Nullable<bool> durumu { get; set; }
        public string stok_kodu { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public string stok_adi { get; set; }
        public string stok_adi_y_disi { get; set; }
        public Nullable<int> barkod_tipi { get; set; }
        public string barkodu { get; set; }
        public string grubu { get; set; }
        public string ara_grubu { get; set; }
        public string alt_grubu { get; set; }
        public string ozel_kodu_1 { get; set; }
        public string ozel_kodu_2 { get; set; }
        public string ozel_kodu_3 { get; set; }
        public string aciklama_1 { get; set; }
        public string aciklama_2 { get; set; }
        public string aciklama_3 { get; set; }
        public Nullable<double> kdv_alis { get; set; }
        public Nullable<double> kdv_satis_prk { get; set; }
        public Nullable<double> kdv_satis_tpt { get; set; }
        public Nullable<double> otv { get; set; }
        public Nullable<double> oiv { get; set; }
        public Nullable<double> otv_birim_fiyati { get; set; }
        public Nullable<double> tevkifat_orani_1 { get; set; }
        public Nullable<double> tevkifat_orani_2 { get; set; }
        public Nullable<int> istisna_kodu { get; set; }
        public Nullable<bool> kdv_85_kanunu { get; set; }
        public Nullable<int> vade_gunu { get; set; }
        public Nullable<double> pazarlamaci_prim_orani { get; set; }
        public Nullable<bool> doviz_hesabi_kullan { get; set; }
        public Nullable<int> doviz_hesabi_birim { get; set; }
        public Nullable<double> pazarlamaci_prim_tutari { get; set; }
        public Nullable<bool> ana_stok { get; set; }
        public Nullable<bool> asorti_sistemi_kullan { get; set; }
        public string markasi { get; set; }
        public string modeli { get; set; }
        public string renk { get; set; }
        public string beden { get; set; }
        public Nullable<long> ana_stok_id { get; set; }
        public Nullable<long> temel_birim_id { get; set; }
        public string varsayilan_birim { get; set; }
        public Nullable<int> vars_miktar { get; set; }
        public Nullable<double> birim_agirlik_net { get; set; }
        public Nullable<double> birim_agirlik_brut { get; set; }
        public Nullable<int> hacim_hesaplama_formulu { get; set; }
        public Nullable<bool> alis_iskonto_1_kullan { get; set; }
        public Nullable<double> alis_iskonto_1 { get; set; }
        public Nullable<bool> alis_iskonto_2_kullan { get; set; }
        public Nullable<double> alis_iskonto_2 { get; set; }
        public Nullable<bool> alis_iskonto_3_kullan { get; set; }
        public Nullable<double> alis_iskonto_3 { get; set; }
        public Nullable<bool> alis_stok_kullan { get; set; }
        public Nullable<double> alis_stok { get; set; }
        public Nullable<bool> satis_iskonto_1_kullan { get; set; }
        public Nullable<double> satis_iskonto_1 { get; set; }
        public Nullable<bool> satis_iskonto_2_kullan { get; set; }
        public Nullable<double> satis_iskonto_2 { get; set; }
        public Nullable<bool> satis_iskonto_3_kullan { get; set; }
        public Nullable<double> satis_iskonto_3 { get; set; }
        public Nullable<bool> satis_stok_kullan { get; set; }
        public Nullable<double> satis_stok { get; set; }
        public Nullable<int> bakiye_uyari { get; set; }
        public string kalite { get; set; }
        public string uretici_firma { get; set; }
        public Nullable<int> olmasi_gereken_stok_limit_minimum { get; set; }
        public Nullable<int> olmasi_gereken_stok_limit_maksimum { get; set; }
        public Nullable<bool> webde_gorunsun { get; set; }
        public string ozellik_tanimi { get; set; }
        public string resim_yolu { get; set; }
        public Nullable<int> izleme_tipi { get; set; }
        public Nullable<bool> partiler_parcalanabilir { get; set; }
        public Nullable<bool> maliyetlerde_eslestirme_yontemini_kullan { get; set; }
        public Nullable<bool> siparis_listesine_ekle { get; set; }
        public Nullable<int> stok_miktari_secim_1 { get; set; }
        public Nullable<int> stok_miktari_secim_2 { get; set; }
        public Nullable<int> stok_miktari_secim_2_liste { get; set; }
        public Nullable<int> yazarkasa_kdv_departmani { get; set; }
        public Nullable<double> mrp_min_tutar { get; set; }
        public Nullable<short> silindi { get; set; }
        public Nullable<int> stok_kayit_yapan { get; set; }
        public Nullable<System.DateTime> stok_kayit_tarihi { get; set; }
        public Nullable<int> stok_degisiklik_yapan { get; set; }
        public Nullable<System.DateTime> stok_degisiklik_tarihi { get; set; }
        public string tevkifat_kodu { get; set; }
    }
}
