//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stok_bagli_stok
    {
        public long id { get; set; }
        public long stok_id { get; set; }
        public long bagli_stok_id { get; set; }
        public double adet { get; set; }
    }
}
