//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stok_birimler
    {
        public long id { get; set; }
        public string birimler { get; set; }
        public Nullable<short> hassasiyet { get; set; }
        public string int_brim_kodu { get; set; }
        public string UnitCode { get; set; }
    }
}
