//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stok_fiyatlar
    {
        public int id { get; set; }
        public int stok_id { get; set; }
        public bool turu { get; set; }
        public int fiyat_no { get; set; }
        public int hesap { get; set; }
        public string tanimi { get; set; }
        public string barkodu { get; set; }
        public Nullable<int> birimi { get; set; }
        public Nullable<double> fiyati { get; set; }
        public Nullable<double> kaynak_fiyat { get; set; }
        public Nullable<int> kaynak_fiyat_no { get; set; }
        public Nullable<double> kar_marji { get; set; }
    }
}
