//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stok_menuler_hareket
    {
        public long id { get; set; }
        public Nullable<long> menu_id { get; set; }
        public Nullable<long> fatura_id { get; set; }
        public Nullable<long> cari_hareket_id { get; set; }
        public Nullable<double> tutar { get; set; }
        public Nullable<long> kaydeden_cari_id { get; set; }
        public Nullable<long> kaydeden { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public Nullable<long> degistiren { get; set; }
        public Nullable<System.DateTime> degistirme_tarihi { get; set; }
    }
}
