//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stok_menuler
    {
        public long id { get; set; }
        public Nullable<short> islem_turu { get; set; }
        public string menu_adi { get; set; }
        public Nullable<double> fiyati { get; set; }
        public Nullable<bool> silindi { get; set; }
        public Nullable<int> kaydeden { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public Nullable<int> degistiren { get; set; }
        public Nullable<System.DateTime> degistirme_tarihi { get; set; }
    }
}
