//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stok_hareket
    {
        public long id { get; set; }
        public Nullable<long> stok_id { get; set; }
        public Nullable<short> tutar_turu { get; set; }
        public Nullable<System.DateTime> tarihi { get; set; }
        public string evrak_no { get; set; }
        public string aciklama { get; set; }
        public Nullable<double> miktari { get; set; }
        public Nullable<double> kpb_tutari { get; set; }
        public Nullable<double> kpb_fiyati { get; set; }
        public Nullable<double> doviz_tutari { get; set; }
        public Nullable<double> doviz_fiyati { get; set; }
        public string ozel_kodu { get; set; }
        public Nullable<long> cari_id { get; set; }
        public Nullable<short> doviz_kullan { get; set; }
        public Nullable<short> kpb_doviz { get; set; }
        public Nullable<int> doviz_birimi_id { get; set; }
        public Nullable<short> doviz_hes_isle { get; set; }
        public Nullable<double> doviz_alis { get; set; }
        public Nullable<double> doviz_satis { get; set; }
        public Nullable<long> depo_id { get; set; }
        public Nullable<double> miktar_2 { get; set; }
        public Nullable<double> kpb_gelen_miktar { get; set; }
        public Nullable<double> kpb_cikan_miktar { get; set; }
        public Nullable<double> kpb_gelen_tutar { get; set; }
        public Nullable<double> kpb_cikan_tutar { get; set; }
        public Nullable<double> doviz_gelen_miktar { get; set; }
        public Nullable<double> doviz_cikan_miktar { get; set; }
        public Nullable<double> doviz_gelen_tutar { get; set; }
        public Nullable<double> doviz_cikan_tutar { get; set; }
        public string entegrasyon { get; set; }
        public Nullable<short> devir { get; set; }
        public Nullable<short> iade { get; set; }
        public Nullable<short> silindi { get; set; }
        public Nullable<long> kaydeden { get; set; }
        public Nullable<long> degistiren { get; set; }
        public Nullable<System.DateTime> degistirme_tarihi { get; set; }
        public Nullable<long> depo_transfer_id { get; set; }
        public string ek_bilgi_1 { get; set; }
        public string ek_bilgi_2 { get; set; }
        public string ek_bilgi_3 { get; set; }
        public string ek_bilgi_4 { get; set; }
        public Nullable<short> maliyete_ekle { get; set; }
        public Nullable<long> birim_2_id { get; set; }
        public Nullable<long> ana_stok_id { get; set; }
        public Nullable<long> sube_id { get; set; }
        public Nullable<short> gm_entegrasyon { get; set; }
        public Nullable<short> transfer_irsaliyesi { get; set; }
        public Nullable<System.DateTime> tarihi_2 { get; set; }
        public Nullable<double> ek_maliyet_kpb { get; set; }
        public Nullable<double> ek_maliyet_doviz { get; set; }
        public Nullable<short> offline_durum { get; set; }
        public Nullable<long> fatura_hareket_id { get; set; }
        public string souce_app { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public Nullable<long> BLSAYIMKODU { get; set; }
    }
}
