//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teklif
    {
        public long id { get; set; }
        public Nullable<short> teklif_durumu { get; set; }
        public Nullable<long> cari_id { get; set; }
        public Nullable<short> teklif_turu { get; set; }
        public Nullable<long> blcrkodu { get; set; }
        public string cari_kodu { get; set; }
        public string ticari_unvani { get; set; }
        public string adi_soyadi { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string vergi_no { get; set; }
        public string vergi_dairesi { get; set; }
        public string tel_1 { get; set; }
        public string faks { get; set; }
        public string adresi { get; set; }
        public string ili { get; set; }
        public string ilcesi { get; set; }
        public string ozel_kodu { get; set; }
        public Nullable<short> kullanici_stok_fiyati { get; set; }
        public string teklif_no { get; set; }
        public Nullable<System.DateTime> tarihi { get; set; }
        public string grubu { get; set; }
        public string aciklama { get; set; }
        public Nullable<short> kdv_durumu { get; set; }
        public Nullable<double> kdv_orani { get; set; }
        public string ek_bilgi_1 { get; set; }
        public string ek_bilgi_2 { get; set; }
        public Nullable<short> iskonto_kul_cari { get; set; }
        public Nullable<double> iskonto_oran_cari { get; set; }
        public Nullable<double> iskonto_tutar_cari { get; set; }
        public Nullable<short> iskonto_kullan_1 { get; set; }
        public Nullable<double> iskonto_oran_1 { get; set; }
        public Nullable<double> iskonto_tutar_1 { get; set; }
        public Nullable<short> iskonto_kullan_2 { get; set; }
        public Nullable<double> iskonto_oran_2 { get; set; }
        public Nullable<double> iskonto_tutar_2 { get; set; }
        public Nullable<short> iskonto_kullan_3 { get; set; }
        public Nullable<double> iskonto_oran_3 { get; set; }
        public Nullable<double> iskonto_tutar_3 { get; set; }
        public Nullable<short> iskonto_kul_stok { get; set; }
        public Nullable<double> iskonto_tutar_stok { get; set; }
        public Nullable<short> iskonto_kul_ozel { get; set; }
        public Nullable<double> iskonto_tutar_ozel { get; set; }
        public Nullable<short> iskonto_kul_alt { get; set; }
        public Nullable<double> iskonto_oran_alt { get; set; }
        public Nullable<double> iskonto_tutar_alt { get; set; }
        public Nullable<double> iskonto_tutar_alt_1 { get; set; }
        public Nullable<double> iskonto_tutar_alt_2 { get; set; }
        public Nullable<short> doviz_kullan { get; set; }
        public string doviz_birim { get; set; }
        public Nullable<short> paz_durumu { get; set; }
        public string paz_personel { get; set; }
        public Nullable<long> paz_pers_id { get; set; }
        public Nullable<double> paz_urun_tutari { get; set; }
        public Nullable<double> paz_urun_orani { get; set; }
        public Nullable<double> paz_isc_orani { get; set; }
        public Nullable<double> paz_isc_tutari { get; set; }
        public string sevk_adresi { get; set; }
        public string sevk_ili { get; set; }
        public string sevk_ilcesi { get; set; }
        public Nullable<double> toplam_alt_kpb { get; set; }
        public Nullable<double> toplam_isk_kbp { get; set; }
        public Nullable<double> toplam_ara_kpb { get; set; }
        public Nullable<double> yuvarlama_kpb { get; set; }
        public Nullable<double> toplam_kdv_kpb { get; set; }
        public Nullable<double> toplam_otv_kpb { get; set; }
        public Nullable<double> toplam_genel_kpb { get; set; }
        public Nullable<double> miktar_1_toplam { get; set; }
        public Nullable<double> miktar_2_toplam { get; set; }
        public Nullable<double> toplam_alt_doviz { get; set; }
        public Nullable<double> toplam_iskonto_doviz { get; set; }
        public Nullable<double> toplam_ara_doviz { get; set; }
        public Nullable<double> yuvarlama_doviz { get; set; }
        public Nullable<double> toplam_kdv_doviz { get; set; }
        public Nullable<double> toplam_genel_doviz { get; set; }
        public Nullable<double> toplam_iskonto_stok { get; set; }
        public Nullable<double> toplam_iskonto_fatura { get; set; }
        public Nullable<double> toplam_iskonto_yuzdesi { get; set; }
        public Nullable<System.DateTime> degistirme_tarihi { get; set; }
        public string kaydeden { get; set; }
        public string degistiren { get; set; }
        public Nullable<short> vade_durumu { get; set; }
        public Nullable<short> ortalama_vade { get; set; }
        public Nullable<short> iptal { get; set; }
        public Nullable<short> silindi { get; set; }
        public Nullable<double> hesaplanan_kdv_doviz { get; set; }
        public Nullable<double> hesaplanan_kdv_kpb { get; set; }
        public Nullable<short> teklif_suresi { get; set; }
        public Nullable<System.DateTime> gecerlilik_tarihi { get; set; }
        public Nullable<System.DateTime> onay_tarih { get; set; }
        public Nullable<short> kpb_doviz { get; set; }
        public string muh_evrak_no { get; set; }
        public Nullable<short> stok_bloke { get; set; }
        public string teklif_bilgisi { get; set; }
        public Nullable<double> bl_firsat_kodu { get; set; }
        public string aciklama_2 { get; set; }
        public Nullable<long> firsat_id { get; set; }
        public Nullable<long> sube_id { get; set; }
        public string sube_kodu { get; set; }
        public string ulkesi { get; set; }
        public string sevk_ulkesi { get; set; }
        public Nullable<double> isk_tutar_cari_doviz { get; set; }
        public Nullable<double> isk_tutar_1_doviz { get; set; }
        public Nullable<double> isk_tutar_2_doviz { get; set; }
        public Nullable<double> isk_tutar_3_doviz { get; set; }
        public Nullable<double> isk_tutar_stok_doviz { get; set; }
        public Nullable<double> isk_tutar_ozel_doviz { get; set; }
        public Nullable<double> isk_tutar_alt_1_doviz { get; set; }
        public Nullable<double> isk_tutar_alt_2_doviz { get; set; }
        public Nullable<double> toplam_isk_stok_doviz { get; set; }
        public Nullable<double> toplam_isk_fatura_doviz { get; set; }
        public Nullable<double> paz_urun_tutari_doviz { get; set; }
        public Nullable<double> paz_isc_tutari_doviz { get; set; }
        public Nullable<short> offline_durum { get; set; }
        public Nullable<short> yuvarlama_kullan { get; set; }
        public string cep_telefonu { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public string e_id { get; set; }
        public Nullable<System.DateTime> e_cevap_tarihi { get; set; }
        public Nullable<int> vade_gunu { get; set; }
        public string e_cevap_hazirlayan { get; set; }
        public string offline_guid { get; set; }
        public string sevk_id { get; set; }
        public string sevk_tanimi { get; set; }
        public string sevk_yetkilisi { get; set; }
        public string sevk_telefonu { get; set; }
        public Nullable<short> belge_onay_durumu { get; set; }
        public string belge_onay_kullanici { get; set; }
        public string kul_stok_fiyat { get; set; }
    }
}
