//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tevkifat
    {
        public string ulke_key { get; set; }
        public string tevkifat_kodu { get; set; }
        public string tevkifat_tanimi { get; set; }
        public string tevkifat_orani { get; set; }
        public string tevkifat_yuzde { get; set; }
    }
}
