//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class turnike_cari_durumlari
    {
        public long id { get; set; }
        public Nullable<long> cari_id { get; set; }
        public Nullable<int> gecis_hakki { get; set; }
        public Nullable<long> kulup_buton_id { get; set; }
        public Nullable<int> kampanya_hakki { get; set; }
        public Nullable<int> kalan_kampanya_hakki { get; set; }
        public Nullable<System.DateTime> islem_tarihi { get; set; }
        public Nullable<System.DateTime> kullanilma_tarihi { get; set; }
    }
}
