//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class turnike_hareketler
    {
        public long id { get; set; }
        public long cari_id { get; set; }
        public long kasa_hareket_id { get; set; }
        public System.DateTime giris_tarihi { get; set; }
        public Nullable<System.DateTime> cikis_tarihi { get; set; }
    }
}
