//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class useful_life_codes
    {
        public string UsefulLifeCode { get; set; }
        public Nullable<short> UsefulLifeTime { get; set; }
        public Nullable<double> UsefulLifeRate { get; set; }
        public Nullable<double> UsefulLifeRate2 { get; set; }
        public Nullable<double> UsefulLifeRate3 { get; set; }
        public string Explanation { get; set; }
    }
}
