//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMENU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yazili_sinav_bilgileri
    {
        public int id { get; set; }
        public string Yazili_Sinav_Okul_Adi { get; set; }
        public string Yazili_Sinav_Okul_Adresi { get; set; }
        public string Yazili_Sinav_Salonu { get; set; }
        public string Yazili_Sinav_Tarih_Saati { get; set; }
    }
}
